#%RAML 1.0
---
title: Individuals Benefits and Credits
version: P1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/benefits-and-credits:
  /hello-world:
    get:
      displayName: Hello World
      description: An endpoint that returns hello world
      is: [headers.acceptHeader]
      responses:
        200:
          description: Return hello world
          body:
            application/json:
              example: "\"Hello World\""

  /:
    get:
      displayName: Benefits and Credits
      description: !include docs/root-description.md
      is: [headers.acceptHeader]
      (annotations.scope): "read:the-scopes-you-have-been-assigned"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:the-scopes-you-have-been-assigned" ] } ]
      (annotations.sandboxData): !include sandbox/root-response.md
      headers:
        Authorization:
          description: An OAuth 2.0 Bearer Token with the scopes you have been assigned.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived universally unique identifier (UUID), typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      responses:
        200:
          description: Use this endpoint to get a list of all available endpoints for Individuals Benefits and Credits.
          body:
            application/json:
              example: !include examples/root-response.json
              type: !include schemas/root-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not Found
                  value:
                    code: NOT_FOUND
  /child-tax-credit:
    get:
      displayName: Child Tax Credits
      description: "test"
      is: [headers.acceptHeader]
      (annotations.scope): "read:the-scopes-you-have-been-assigned"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:the-scopes-you-have-been-assigned" ] } ]
      (annotations.sandboxData): "test"
      headers:
        Authorization:
          description: An OAuth 2.0 Bearer Token with the scopes you have been assigned.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived universally unique identifier (UUID), typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromDate:
          description: The start date for Child Tax Credit data requested.
          type: string
          required: true
          example: 2016-01-01
        toDate:
         description: The end date for Child Tax Credit data requested. If missing, it defaults to today's date.
         type: string
         example: 2017-03-01
      responses:
        200:
          description: Use this endpoint to get an individual’s Child Tax Credit details for the requested time period. Data is not available before 2015.
          body:
            application/json:
              example: "test"
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not Found
                  value:
                    code: NOT_FOUND
  /working-tax-credit:
    get:
      displayName: Working Tax Credits
      description: "test"
      is: [headers.acceptHeader]
      (annotations.scope): "read:the-scopes-you-have-been-assigned"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:the-scopes-you-have-been-assigned" ] } ]
      (annotations.sandboxData): "test"
      headers:
        Authorization:
          description: An OAuth 2.0 Bearer Token with the scopes you have been assigned.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived universally unique identifier (UUID), typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          required: true
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromDate:
          description: The start date for Working Tax Credit data requested.
          type: string
          required: true
          example: 2016-01-01
        toDate:
         description: The end date for Working Tax Credit data requested. If missing, it defaults to today's date.
         type: string
         example: 2017-03-01
      responses:
        200:
          description: Use this endpoint to get an individual’s Working Tax Credit details for the requested time period. Data is not available before 2015.
          body:
            application/json:
              example: "test"
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not Found
                  value:
                    code: NOT_FOUND