#%RAML 1.0
---
title: Individuals Benefits and Credits
version: P1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/hello-world:
  get:
    displayName: Hello World
    description: An endpoint that returns hello world
    is: [headers.acceptHeader]
    responses:
      200:
        description: Return hello world
        body:
          application/json:
            example: "\"Hello World\""


/:
  get:
    displayName: Benefits and Credits
    description: A placeholder endpoint for root that will throw an exception
    is: [headers.acceptHeader]
    responses:
      500:
        description: Throws an exception

/child-tax-credits:
  get:
    displayName: Child Tax Credits
    description: A placeholder endpoint for child tax credits that will throw an exception
    is: [headers.acceptHeader]
    responses:
      500:
        description: Throws an exception

/working-tax-credits:
  get:
    displayName: Working Tax Credits
    description: A placeholder endpoint for working tax credits that will throw an exception
    is: [headers.acceptHeader]
    responses:
      500:
        description: Throws an exception